
server:
  port: 8082
#rpc 协议端口及注册中心地址
com:
  alipay:
    sofa:
      rpc:
        registry-address: nacos://172.16.31.210:31256/public
        bolt-port: 12202
#开启sql语句日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

management:
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: sofa-demo-consumer
  # 配置数据源信息
  datasource:
    dynamic:
      # 设置默认的数据源或者数据源组,默认值即为master
      primary: master
      # 严格匹配数据源,默认false.true未匹配到指定数据源时抛异常,false使用默认数据源
      strict: false
      datasource:
        master:
          url: jdbc:mysql://172.16.31.210:31001/sofaboot?characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: dev
          password: Aa123456
        slave_1:
          url: jdbc:mysql://172.16.31.210:31001/sofaboot?characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: dev
          password: Aa123456
#seata 配置
seata:
  service:
    vgroup-mapping:
      default_tx_group: default
    grouplist:
      default: 172.18.44.35:8091
